---
version: '3'

networks:
  host_bridge:
    name: qnet-static-eth0-076754
    external: true

services:
  bazarr:
    image: linuxserver/bazarr:latest
    container_name: Bazarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /share/CACHEDEV1_DATA/Container/Bazarr:/config
      - /share/CACHEDEV2_DATA/Media/Media:/data
    networks:
      host_bridge:
        ipv4_address: 192.168.100.16
    ports:
      - 80:80
