---
version: '3'

networks:
  host_bridge:
    name: qnet-static-eth0-076754
    external: true

services:
  ombi:
    image: linuxserver/ombi:latest
    container_name: Ombi
    networks:
      host_bridge:
        ipv4_address: 192.168.100.20
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /share/CACHEDEV1_DATA/Container/Ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
