---
version: '3'

networks:
  host_bridge:
    driver: qnet
    driver_opts:
      iface: "eth0"
    ipam:
      driver: qnet
      options:
        iface: "eth0"
      config:
        - subnet: 192.168.60.0/24
          gateway: 192.168.60.1

services:
  openspeedtest:
    image: openspeedtest/latest:latest
    container_name: OpenSpeedTest
    restart: unless-stopped
    environment:
      - CHANGE_CONTAINER_PORTS=True
      - HTTP_PORT=80
      - HTTPS_PORT=443
    networks:
      host_bridge:
        ipv4_address: 192.168.60.18
