---
version: '3'

networks:
  host_bridge:
    name: qnet-static-eth0-076754
    external: true

services:
  plex:
    image: linuxserver/plex:latest
    container_name: Plex
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /share/CACHEDEV1_DATA/Container/Plex:/config
      - /share/CACHEDEV2_DATA/Media/Media:/data
      - /share/CACHEDEV1_DATA/Container/Plex/dev/dri:/dev/dri
    networks:
      host_bridge:
        ipv4_address: 192.168.100.10
    ports:
      - 1900:1900/udp
      - 5353:5353/udp
      - 8324:8324/udp
      - 32400:32400
      - 32410-32414:32410-32414/udp
      - 32469:32469
    devices:
      - /share/CACHEDEV1_DATA/Container/Plex/dev/dri:/dev/dri
