---
version: '3'

networks:
  host_bridge:
    name: qnet-static-eth0-076754
    external: true

services:
  radarr:
    image: linuxserver/radarr:latest
    container_name: Radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /share/CACHEDEV1_DATA/Container/Radarr:/config
      - /share/CACHEDEV2_DATA/Media/Media/Movies:/data/Movies
      - /share/CACHEDEV2_DATA/Media/SABnzbd/downloads/radarr:/data/SABnzbd/downloads/radarr
    networks:
      host_bridge:
        ipv4_address: 192.168.100.14
