---
version: '3'

networks:
  host_bridge:
    driver: qnet
    driver_opts:
      iface: "eth0"
    ipam:
      driver: qnet
      options:
        iface: "eth0"
      config:
        - subnet: 192.168.60.0/24
          gateway: 192.168.60.1

services:
  resilio-sync:
    image: linuxserver/resilio-sync:latest
    container_name: ResilioSync
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /share/CACHEDEV1_DATA/Container/Resilio:/config
      - /share/CACHEDEV2_DATA/Media:/downloads
      - /share/CACHEDEV2_DATA/Media:/sync
    networks:
      host_bridge:
        ipv4_address: 192.168.60.11
