---
version: '3'

networks:
  host_bridge:
    name: qnet-static-eth0-076754
    external: true

services:
  sabnzbd:
    image: linuxserver/sabnzbd:latest
    container_name: Sabnzbd
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /share/CACHEDEV1_DATA/Container/Sabnzbd:/config
      - /share/CACHEDEV2_DATA/Media:/data
    networks:
      host_bridge:
        ipv4_address: 192.168.100.12
