---
version: '3'

networks:
  host_bridge:
    name: qnet-static-eth0-076754
    external: true

services:
  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
    volumes:
      - /share/CACHEDEV1_DATA/Container/sonarr:/config
      - /share/CACHEDEV2_DATA/Media/Media
    networks:
      host_bridge:
        ipv4_address: 192.168.100.15
    ports:
      - 8989:8989

    # volumes:
    #   - /path/to/data:/config
    #   - /path/to/tvseries:/tv #optional
    #   - /path/to/downloadclient-downloads:/downloads #optional
