networks:
  internal:
    external: True
services:
  bazarr:
    environment:
      PGID: 568
      PUID: 568
      TZ: America/New_York
    image: linuxserver/bazarr:latest
    networks:
      internal: Null
    restart: unless-stopped
    volumes:
      - /mnt/zPool2/data/app_configs/bazarr:/config
      - /mnt/zPool2/data:/data
