name: immich
networks:
  immich_bridge:
    driver: bridge
  macvlan_net:
    external: True
services:
  database:
    command: >-
      postgres -c shared_preload_libraries=vectors.so -c 'search_path="$$user",
      public, vectors' -c logging_collector=on -c max_wal_size=2GB -c
      shared_buffers=512MB -c wal_compression=on
    container_name: immich_postgres
    environment:
      POSTGRES_DB: immich
      POSTGRES_INITDB_ARGS: '--data-checksums'
      POSTGRES_PASSWORD: G0ldf1sh
      POSTGRES_USER: postgres
    healthcheck:
      interval: 5m
      start_interval: 30s
      start_period: 5m
      test: >-
        pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" ||
        exit 1; Chksum="$$(psql --dbname="$${POSTGRES_DB}"
        --username="$${POSTGRES_USER}" --tuples-only --no-align
        --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM
        pg_stat_database')"; echo "checksum failure count is $$Chksum"; [
        "$$Chksum" = '0' ] || exit 1
    image: >-
      docker.io/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    networks:
      immich_bridge: Null
    restart: always
    volumes:
      - /mnt/zPool2/data/immich/postgres:/var/lib/postgresql/data
  immich-machine-learning:
    container_name: immich_machine_learning
    healthcheck:
      disable: False
    image: ghcr.io/immich-app/immich-machine-learning:release
    networks:
      immich_bridge: Null
    restart: always
    volumes:
      - model-cache:/cache
  immich-server:
    container_name: immich_server
    depends_on:
      - redis
      - database
    devices:
      - /dev/dri:/dev/dri
    environment:
      DB_DATABASE_NAME: immich
      DB_PASSWORD: G0ldf1sh
      DB_USERNAME: postgres
    healthcheck:
      disable: False
    image: ghcr.io/immich-app/immich-server:release
    networks:
      immich_bridge: Null
      macvlan_net:
        ipv4_address: 192.168.50.6
    restart: always
    volumes:
      - /mnt/zPool2/data/immich/library:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
  redis:
    container_name: immich_redis
    healthcheck:
      test: redis-cli ping || exit 1
    image: >-
      docker.io/redis:6.2-alpine@sha256:eaba718fecd1196d88533de7ba49bf903ad33664a92debb24660a922ecd9cac8
    networks:
      immich_bridge: Null
    restart: always
volumes:
  model-cache: Null
