networks:
  macvlan_net:
    external: True
services:
  app:
    environment:
      TZ: America/New_York
      WEBPASSWORD: WhyYouWant2Know?
    image: pihole/pihole:latest
    networks:
      macvlan_net:
        ipv4_address: 192.168.50.2
    restart: unless-stopped
    volumes:
      - /mnt/zPool2/data/app_configs/pihole/config:/etc/pihole
