networks:
  internal:
    external: True
  external:
    external: True
services:
  prowlarr:
    environment:
      PGID: 568
      PUID: 568
      TZ: America/New_York
    image: linuxserver/prowlarr:latest
    networks:
      internal:
      external:
        ipv4_address: 192.168.50.22
    restart: unless-stopped
    volumes:
      - /mnt/zPool2/data/app_configs/prowlarr:/config
