networks:
  internal:
    external: True
services:
  radarr:
    environment:
      PGID: 568
      PUID: 568
      TZ: America/New_York
    image: linuxserver/radarr:latest
    networks:
      internal:
    restart: unless-stopped
    volumes:
      - /mnt/zPool2/data/app_configs/radarr:/config
      - /mnt/zPool2/data:/data
