networks:
  internal:
    external: True
  external:
    external: True
services:
  radarr:
    environment:
      PGID: 568
      PUID: 568
      TZ: America/New_York
    image: linuxserver/radarr:latest
    networks:
      internal:
      external:
        ipv4_address: 192.168.50.23
    restart: unless-stopped
    volumes:
      - /mnt/zPool2/data/app_configs/radarr:/config
      - /mnt/zPool2/data:/data
