networks:
  internal:
    external: True
  external:
    external: True
services:
  recyclarr:
    environment:
      CRON_SCHEDULE: '@daily'
      RECYCLARR_CREATE_CONFIG: True
      TZ: America/New_York
    image: ghcr.io/recyclarr/recyclarr:latest
    networks:
      internal:
      external:
        ipv4_address: 192.168.50.26
    restart: unless-stopped
    volumes:
      - /mnt/zPool2/data/app_configs/recyclarr:/config
