networks:
  internal:
    external: True
services:
  recyclarr:
    environment:
      CRON_SCHEDULE: '@daily'
      RECYCLARR_CREATE_CONFIG: True
      TZ: America/New_York
    image: ghcr.io/recyclarr/recyclarr:latest
    networks:
      internal:
    restart: unless-stopped
    volumes:
      - /mnt/zPool2/data/app_configs/recyclarr:/config
