networks:
  external:
    external: True
services:
  resilio:
    environment:
      PGID: 568
      PUID: 568
      TZ: America/New_York
    image: linuxserver/resilio-sync:latest
    networks:
      external:
        ipv4_address: 192.168.50.27
    restart: unless-stopped
    volumes:
      - /mnt/zPool2/data/app_configs/resilio:/config
      - /mnt/zPool2/data:/sync
