networks:
  internal:
    external: True
services:
  sabnzbd:
    environment:
      PGID: 568
      PUID: 568
      TZ: America/New_York
    image: linuxserver/sabnzbd:latest
    networks:
      internal:
    restart: unless-stopped
    volumes:
      - /mnt/zPool2/data/app_configs/sabnzbd:/config
      - /mnt/zPool2/data:/data
