networks:
  internal:
    external: True
services:
  sonarr:
    environment:
      PGID: 568
      PUID: 568
      TZ: America/New_York
    image: linuxserver/sonarr:latest
    networks:
      internal:
    restart: unless-stopped
    volumes:
      - /mnt/zPool2/data/app_configs/sonarr:/config
      - /mnt/zPool2/data:/data
