---
version: '3'

networks:
  host_bridge:
    driver: qnet
    driver_opts:
      iface: "eth0"
    ipam:
      driver: qnet
      options:
        iface: "eth0"
      config:
        - subnet: 192.168.60.0/24
          gateway: 192.168.60.1

services:
  resilio-sync:
    image: pihole/pihole:latest
    container_name: PiHole
    restart: unless-stopped
    environment:
      - PUID=0
      - PGID=0
      - TZ=America/New_York
      - WEBPASSWORD=WhyYouWant2Know?
    volumes:
      - /share/CACHEDEV1_DATA/Container/PiHole/config:/config
    networks:
      host_bridge:
        ipv4_address: 192.168.60.2
