---
version: '3'

networks:
  host_bridge:
    driver: qnet
    driver_opts:
      iface: "eth0"
    ipam:
      driver: qnet
      options:
        iface: "eth0"
      config:
        - subnet: 192.168.60.0/24
          gateway: 192.168.60.1

services:
  watchtower:
    image: containrrr/watchtower
    container_name: WatchTower
    restart: unless-stopped
    environment:
      - TZ=America/New_York
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_DEBUG=true
      - WATCHTOWER_LOG_LEVEL=info
      - WATCHTOWER_REMOVE_VOLUMES=true
      - WATCHTOWER_SCHEDULE=0 0 * * * *
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      host_bridge:
        ipv4_address: 192.168.60.17
